name: cointracker
description: CoinTracker APP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  firebase_auth: ^1.1.4
  google_sign_in: ^5.0.3
  url_launcher: ^6.0.20

  #Image Selector profile
  image_picker: ^0.8.4+9
  #upload img to server
  cloudinary_public: ^0.11.0

  flutter_native_splash: ^2.0.4
  flutter_launcher_icons: ^0.9.2

  #biometric login
  local_auth: ^1.1.11

  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/coin_logos/
#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ff1616"

#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#191919"
  image: assets/images/splash.png
  android: true
  ios: false